/* eslint-disable */
// DO NOT EDIT this file gen by protos/data/scalars/scalars.proto
import axios, { AxiosResponse } from "axios";
import * as student from "protos/data/student/student.d.ts";
export interface Scalars {
  double: number;
  float: number;
  int32: number;
  int64: number;
  uint32: number;
  uint64: number;
  sint32: number;
  sint64: number;
  fixed32: number;
  fixed64: number;
  sfixed32: number;
  sfixed64: number;
  bool: boolean;
  string: string;
  bytes: number[];
  name: string;
  User: User;
  Users: User[];
  Student: student.Student[];
}
export interface User {
  Name: string;
  Age: string;
}
