// DO NOT EDIT this file gen by protos/kitchen/kitchen.proto
import axios, { AxiosResponse } from "axios";


interface Kitchen {
  
  style: Style;
  
  sink: *Sink;
  
  utensils: string[];
  
  dish_counts: map[string]uint32;
  
  wall_colors: []*Color;
  
  appliance_colors: map[string]*Color;
  
}


interface Color {
  
  pantone: string;
  
  rgb: *Color_RGB;
  
  cmyk: *Color_CMYK;
  
  alpha: float64;
  
}


interface SauteRequest {
  
}


interface SauteResponse {
  
}


interface IceRequest {
  
}


interface IceResponse {
  
}


interface GroceryItem {
  
}


interface LoadSummary {
  
}


interface DrinkOrder {
  
}


interface PreparedDrink {
  
}


interface RGB {
  
  r: uint32;
  
  g: uint32;
  
  b: uint32;
  
}


interface CMYK {
  
  c: uint32;
  
  m: uint32;
  
  y: uint32;
  
  k: uint32;
  
}