package ts

var tsTemplate = `
/* eslint-disable */
// DO NOT EDIT this file gen by {{.ProtoFileName}}
import axios, { AxiosResponse } from "axios";

{{- range .Imports}}
import * as {{.PackageName}} from "{{.PackagePath}}";
{{- end}}

{{- range .Messages }}
export interface {{ .Name}} {
  {{- range .Fields}}
    {{- if .IsOption}}
      {{.Name}}?: {{.TypeName}};
    {{- else if .IsRepeated}}
      {{.Name}}: {{.TypeName}}[];
    {{- else}}
      {{.Name}}: {{.TypeName}};
    {{- end}}
  {{- end}}
}
{{- end}}

{{- range .Enums}}
export enum {{.Name}}{
  {{- range .Fields}}
    {{.}},
  {{- end}}
}
{{- end}}

{{- range .Services}}
	{{- range .Methods}}	
	const {{.Name}} = (client: AxiosInstance) => async (
		request: {{.Request}}
	): Promise<AxiosResponse<{{.Response}}>> => {
		const result = await client.post("/{{.Url}}", request);
		return result.data;
	};
	{{- end}}
{{- end}}

{{- range $i, $service := .Services}}
	{{- range .Methods}}
	export const {{$service.Name}} = (client: AxiosInstance) => {
		{{.Name}}: {{.Name}}(client);
	};
	{{- end}}
{{- end}}
`
