package ts

var tsTemplate = `
// DO NOT EDIT this file gen by {{.ProtoFileName}}
import axios, { AxiosResponse } from "axios";

{{ range .Messages }}
interface {{ .Name}} {
  {{range .Fields}}
  {{.Name}}: {{.TypeName}};
  {{end}}
}
{{end}}
`
