
/* eslint-disable */
// DO NOT EDIT this file gen by protos/handler/student/student.proto
import axios, { AxiosResponse,AxiosRequestConfig} from "axios";
export interface Student {
      Name: string;
      Age: number;
}
