
/* eslint-disable */
// DO NOT EDIT this file gen by protos/data/student/student.proto
import axios, { AxiosResponse } from "axios";
export interface Student {
      Name: string;
      Age: number;
}
