
/* eslint-disable */
// DO NOT EDIT this file gen by protos/handler/scalars/scalars.proto
import axios, { AxiosResponse,AxiosRequestConfig} from "axios";
import * as student from "protos/handler/student/student";
export interface Scalars {
      UserType?: UserType;
      Student: student.Student;
}
export interface User {
      Name: string;
      Age: string;
}
export interface GetUserListRequest {
}
export interface GetUserListResponse {
}
export enum UserType{
    Worker,
    Man,
    Woman,
}	
	const GetUserList = (client: AxiosInstance,config?: AxiosRequestConfig) => async (
		request: GetUserListRequest
	): Promise<AxiosResponse<GetUserListResponse>> => {
		const result = await client.post("/.scalars.UserService.GetUserList", request,config);
		return result.data;
	};
	export const UserService = (client: AxiosInstance,config?: AxiosRequestConfig) => {
		GetUserList: GetUserList(client,config);
	};
