/* eslint-disable */
// DO NOT EDIT this file gen by protos/handler/scalars/scalars.proto
import axios, { AxiosResponse, AxiosRequestConfig } from "axios";
import * as student from "protos/handler/student/student";
export interface Scalars {
  UserType?: UserType;
  Student: student.Student;
}
export interface User {
  Name: string;
  Age: string;
}
export interface GetUserListRequest {}
export interface GetUserListResponse {}
export enum UserType {
  Worker,
  Man,
  Woman,
}
const GetUserList = (config?: AxiosRequestConfig) => async (
  request: GetUserListRequest
): Promise<AxiosResponse<GetUserListResponse>> => {
  const result = await axios.post(
    "/.scalars.UserService.GetUserList",
    request,
    config
  );
  return result.data;
};
export const UserService = (config?: AxiosRequestConfig) => {
  GetUserList: GetUserList(config);
};
